# common aliases
alias ..="cd .."
alias la="ls -la"
alias back="cd $OLDPWD"
alias snano="sudo nano"
alias ebash="sudo nano ~/.bashrc"
alias vs="code ."
alias c="clear"
alias h="history"
alias update="echo '<------ 🚀 Running update ------>' && sudo apt update -y && echo '<------ 🚀 Updated ------>' && sudo apt dist-upgrade -y && sudo apt upgrade -y && echo '<------ 🚀 Upgraded ------>' && sudo apt autoremove -y && sudo apt autoclean -y && echo '<------ 🚀 Cleaned ------>'"
alias psql="sudo service postgresql start"
alias y="yarn"
alias ys="yarn start"
alias yd="yarn dev"
alias ya="yarn add"
alias yc="yarn cache clean"
alias yb="yarn build"

# git aliases
alias gcl="git clone"
alias gs="git status"
alias gd="git diff"
alias ga="git add ."
alias gcm="git commit -m"
alias gcam="git commit -am"
alias gps="git push"
alias gpu="git pull"
alias gpom="git pull origin master"
alias gpos="git pull origin staging"
alias gconb="git checkout -B"
alias gcob="git checkout"
alias gcobm="git checkout master"
alias gcobs="git checkout staging"
